# Configuration for the protoveneer tool.

package: genai

protoImportPath: cloud.google.com/go/ai/generativelanguage/apiv1beta/generativelanguagepb
supportImportPath: github.com/google/generative-ai-go/internal/support

types:
    HarmCategory:
      protoPrefix: HarmCategory_HARM_CATEGORY_
      docVerb: specifies

    SafetySetting_HarmBlockThreshold:
      name: HarmBlockThreshold
      protoPrefix: SafetySetting_BLOCK_
      veneerPrefix: HarmBlock
      docVerb: specifies
      valueNames:
        SafetySetting_HARM_BLOCK_THRESHOLD_UNSPECIFIED: HarmBlockUnspecified

    SafetyRating_HarmProbability:
      name: HarmProbability
      protoPrefix: SafetyRating_
      docVerb: specifies
      valueNames:
        SafetyRating_HARM_PROBABILITY_UNSPECIFIED: HarmProbabilityUnspecified

    Candidate_FinishReason:
      name: FinishReason
      protoPrefix: Candidate_
      fields:
        GroundingAttributions:
          omit: true

    GenerateContentResponse_PromptFeedback_BlockReason:
      name: BlockReason
      protoPrefix: GenerateContentResponse_PromptFeedback_

    Type:
      protoPrefix: Type_

    Content:
      fields:
        Parts:
          type: '[]Part'

    Blob:
      fields:
        MimeType:
          name: MIMEType
      docVerb: contains

    FunctionCall:
    FunctionResponse:
    FunctionDeclaration:

    GenerationConfig:
      fields:
        Temperature:
          type: float32
        TopP:
          type: float32
        TopK:
          type: int32
        CandidateCount:
          type: int32
        MaxOutputTokens:
          type: int32

    SafetySetting:

    SafetyRating:
      docVerb: 'is the'

    CitationMetadata:

    CitationSource:
      docVerb: contains
      fields:
        Uri:
          name: URI
        License:
          type: string

    Candidate:
      fields:
        Index:
          type: int32
        GroundingAttributions:
          omit: true

    GenerateContentResponse_PromptFeedback:
      name: PromptFeedback
      docVerb: contains

    CountTokensResponse:

    Tool:
      docVerb: contains

    Schema:


# Omit everything not explicitly configured.
omitTypes:
  - '*'

converters:
  Part: partToProto, partFromProto
